language: node_js
node_js:
  - "8"
  - "9"
  - "10"
install:
  - npm install
  - export PATH=$PWD/node_modules/.bin:$PATH
script:
  - npm run clean
  - npm run test
branches:
  only:
    - master
dist: trusty
